# vim: set filetype=yaml expandtab tabstop=2 shiftwidth=2 softtabstop=2 background=dark :

- name: alter ERIGONES_MGMT_WORKERS in local_config
  lineinfile:
    state=present
    dest=/opt/erigones/core/celery/local_config.py
    regexp="^ERIGONES_MGMT_WORKERS *=.*$"
    line="ERIGONES_MGMT_WORKERS = ({% for mgmtnode in mgmt_nodes %}'mgmt@{{ mgmtnode }}.local',{% endfor %})"
  notify: restart esdc services

- name: alter BROKER_URL in local_config
  replace:
    dest=/opt/erigones/core/celery/local_config.py
    regexp="^(BROKER_URL *=.*$)"
    replace="BROKER_URL = 'amqp://{{ rabbitmq.user }}:{{ rabbitmq.password }}@{{ rabbitmq.host }}:{{ rabbitmq.port}}/{{ rabbitmq.vhost }}'"
  notify: restart esdc services

- name: alter CELERY_RESULT_BACKEND in local_config
  replace:
    dest=/opt/erigones/core/celery/local_config.py
    regexp="^(CELERY_RESULT_BACKEND *=.*)"
    replace="CELERY_RESULT_BACKEND = 'redis://:{{ redis.password }}@{{ cluster_vip }}:6379/0'"
  notify: restart esdc services

# modify "HOST: ip.add.re.ss" to add current cluster VIP
- name: alter DB IP in local_settings
  replace:
    dest=/opt/erigones/core/local_settings.py
    regexp="('HOST'[ \t]*:[ \t]*)'[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'"
    replace="\1'{{ cluster_vip }}'"
  notify: restart esdc services

- meta: flush_handlers

- name: ensure web services are started
  service: name="{{ item }}" state=started enabled=yes
  with_items: '{{ services_systemd_enabled }}'
