#!/usr/perl5/bin/perl 
#
# zabbix_arcstat 
#
# ZFS ARC statistics for Zabbix monitoring
#

use strict;
use Sun::Solaris::Kstat;

my $kstat = Sun::Solaris::Kstat->new();

my $arcstats = $kstat->{zfs}->{0}->{arcstats};

my $arc_size = $arcstats->{size};
my $mru_size = $arcstats->{p};
my $target_size = $arcstats->{c};
my $mfu_size = $target_size - $mru_size;

my $arc_hits = $arcstats->{hits};
my $arc_misses = $arcstats->{misses};
my $arc_total_accesses = $arc_hits + $arc_misses;

my $arc_hits_perc = 100*($arc_hits / $arc_total_accesses);
my $arc_misses_perc = 100*($arc_misses / $arc_total_accesses);

my $l2_size = $arcstats->{l2_size};

my ($l2_hits, $l2_misses);
my ($l2_hits_perc, $l2_misses_perc);
my ($l2_read_bytes, $l2_write_bytes);

if ($l2_size != 0) {

	my $l2_hits = $arcstats->{l2_hits};
	my $l2_misses = $arcstats->{l2_misses};
	my $l2_accesses_total = $l2_hits + $l2_misses;

	$l2_hits_perc = 100*($l2_hits / $l2_accesses_total);
	$l2_misses_perc = 100*($l2_misses / $l2_accesses_total);

	$l2_read_bytes = $arcstats->{l2_read_bytes};
	$l2_write_bytes = $arcstats->{l2_write_bytes};
	
}

my $param = $ARGV[0];

# ARC accesses
if    ($param eq 'arc_hits') 		{ print "$arc_hits\n"; }
elsif ($param eq 'arc_misses')		{ print "$arc_misses\n"; }
# ARC size breakdown
elsif ($param eq 'arc_size') 		{ print "$arc_size\n"; }
elsif ($param eq 'mfu_size')		{ print "$mfu_size\n"; }
elsif ($param eq 'mru_size')		{ print "$mru_size\n"; }
elsif ($param eq 'target_size')		{ print "$target_size\n"; }
# ARC efficiency
elsif ($param eq 'arc_hit_perc')	{ print "$arc_hits_perc\n"; }
elsif ($param eq 'arc_miss_perc')	{ print "$arc_misses_perc\n"; }
# L2ARC accesses
elsif ($param eq 'l2_hits')			{ print "$l2_hits\n"; }
elsif ($param eq 'l2_misses')		{ print "$l2_misses\n"; }
# L2ARC efficiency
elsif ($param eq 'l2_hits_perc')	{ print "$l2_hits_perc\n"; }
elsif ($param eq 'l2_misses_perc')	{ print "$l2_misses_perc\n"; }
# L2ARC throughput
elsif ($param eq 'l2_read_bytes')	{ print "$l2_read_bytes\n"; }
elsif ($param eq 'l2_write_bytes')	{ print "$l2_write_bytes\n"; }
# No $param
else { ; }
